### ISSUE TITLE
Whole_File doesn't lock the whole file.

### ISSUE THREAD

**Issue by Rombobeorn** [Blady-Com/florist#2]
Hello, is this where Florist is maintained now? In that case I have some bugs to report.

The procedures in POSIX.File_Locking don't properly lock the whole file when Whole_File is True. They look up the file's current size with POSIX.IO.File_Size, and then call fcntl to lock that many bytes. This does not work when another process appends to the file concurrently. Even if the file doesn't grow between the calls to File_Size and fcntl, locking only the file's current size doesn't prevent another process from locking a region past the end and appending to the file.

Quoting the POSIX Programmer's Manual at https://man7.org/linux/man-pages/man3/fcntl.3p.html:

       Locks may start and extend beyond the current end of a file, but
       shall not extend before the beginning of the file. A lock shall
       be set to extend to the largest possible value of the file offset
       for that file by setting l_len to 0. If such a lock also has
       l_start set to 0 and l_whence is set to SEEK_SET, the whole file
       shall be locked.

Replace all three calls to File_Size in posix-file_locking.adb with zero.

**Comment by Blady-Com** [comment]
Thanks for reporting.
I fix it in the way described in this [commit](https://github.com/Blady-Com/florist/commit/7fdcc754bd2b4ada063746ab6a242afac8e811b8).
