### ISSUE TITLE
Retrying is broken in Generic_Write.

### ISSUE THREAD

**Issue by Rombobeorn** [Blady-Com/florist#3]
POSIX.IO.Generic_Write tries to write repeatedly, but will break if it doesn't get to write the whole amount in the first attempt.

If the first attempt consumes less than half of the data, then Generic_Write sets the size too small in the second attempt, because it subtracts the written amount twice: first on line 484, and then again on line 480 in the next iteration.

If the first attempt consumes more than half of the data but not all of it, then there will be an integer underflow when To_Write < Written on line 480.

Change "To_Write - Written" to just "To_Write" on line 480.

**Comment by Blady-Com** [comment]
Good catch, thanks for reporting.
Fix in this [commit](https://github.com/Blady-Com/florist/commit/c485477aa7009c2687e23ea2464be2f9c96cefa9).
