### ISSUE TITLE
"iff" means "if and only if"

### ISSUE THREAD

**Issue by Rombobeorn** [Blady-Com/florist#4]
Regarding the commit on 16 October 2020, "iff" does not look like a typo. See https://en.wiktionary.org/wiki/iff

**Comment by Blady-Com** [comment]
Thank you for bringing that point to my attention, I didn't know that abbreviation.
Fix in this [commit](https://github.com/Blady-Com/florist/commit/858120577e3d3f24438458ebff45efe1e39f68f8).
