### ISSUE TITLE
Default value of Timeout parameter in the Poll procedure is misleading.

### ISSUE THREAD

**Issue by charlie5** [Blady-Com/florist#5]
The default of 'Wait_Indefinitely' is defined as 0. A timeout of 0 in a poll operation returns immediately.

Regards.

**Comment by Blady-Com** [comment]
When using Wait_Indefinitely, the Timeout parameter is compared to Wait_Indefinitely value, if match then the timer access is set to null that should give to the desired behavior.
See for instance this [line](https://github.com/Blady-Com/florist/blob/master/libsrc/posix-event_management.adb#L173).
Best Pascal.

**Comment by charlie5** [comment]
I was referring to the 'Poll' function, which takes a C 'int' for the 'Timeout' parameter.


"Note that the timeout interval will be rounded up to the system
       clock granularity, and kernel scheduling delays mean that the
       blocking interval may overrun by a small amount.  Specifying a
       negative value in timeout means an infinite timeout.  Specifying
       a timeout of zero causes poll() to return immediately, even if no
       file descriptors are ready."

The timeout is the number of milliseconds to wait, so I think that the given timeout should not be multiplied by 1000 as is done here ...

Response_Count := Natural (Check_NNeg (c_poll (
         fds     => Files (Files'First).C'Unchecked_Access,
         nfds    => unsigned (Files'Length),
         timeout => int (Long_Long_Integer (Timeout * 1000)))));


Best regards.

**Comment by Blady-Com** [comment]
> I was referring to the 'Poll' function, which takes a C 'int' for the 'Timeout' parameter.

Sorry I missed it.

> "Note that the timeout interval will be rounded up to the system clock granularity, and kernel scheduling delays mean that the blocking interval may overrun by a small amount. Specifying a negative value in timeout means an infinite timeout. Specifying a timeout of zero causes poll() to return immediately, even if no file descriptors are ready."

As value zero is meaningful and is the default of Wait_Indefinitely, I propose to change the default value parameter to -1:

```ada
   procedure Poll
      (Files          : in out Poll_FD_Array;
       Response_Count : out    Natural;
       Timeout        :        Duration := -1.0);
```
 
What is your feedback?

> The timeout is the number of milliseconds to wait, so I think that the given timeout should not be multiplied by 1000 as is done here ...

If I remember well, the Duration type is expected to be in second, isn't it?

Best regards, Pascal.

**Comment by charlie5** [comment]
> 
> As value zero is meaningful and is the default of Wait_Indefinitely, I propose to change the default value parameter to -1:
> 
> ```ada
>    procedure Poll
>       (Files          : in out Poll_FD_Array;
>        Response_Count : out    Natural;
>        Timeout        :        Duration := -1.0);
> ```
> 
> What is your feedback?

Sounds good. Perhaps use a Duration constant ?

```ada
    No_Timeout : constant Duration;

    procedure Poll
       (Files          : in out Poll_FD_Array;
        Response_Count : out    Natural;
        Timeout        :        Duration := No_Timeout;

...

private
    No_Timeout : constant Duration := -1.0;

```
 
> > The timeout is the number of milliseconds to wait, so I think that the given timeout should not be multiplied by 1000 as is done here ...
> 
> If I remember well, the Duration type is expected to be in second, isn't it?
> 
Ah yes, my mistake, sorry. I wasn't thinking straight :/ .

**Comment by Rombobeorn** [comment]
The Ada Reference Manual specifies only that Duration exists and is a fixed-point type. I can't find anything about what it's supposed to represent. However, the subprograms in posix.adb that handle Timespec and Duration assume that Duration represents seconds, so for consistency the rest of Florist should do the same. Therefore multiplying by 1000 in Poll is correct.

A default of -1 second for Poll is not the best choice. Citing the POSIX Programmer's Manual, man 3p poll:

  If the value of timeout is -1, poll() shall block until a requested event occurs or until the call is interrupted.

The Posix manpage leaves other negative values unspecified, so Poll should make sure to pass exactly -1 ms to c_poll when Timeout = Wait_Indefinitely, not -1000 ms.

Wait_Indefinitely = 0 causes a problem with Select_File too. Citing the POSIX Programmer's Manual, man 3p pselect:

  To effect a poll, the timeout parameter should not be a null pointer, and should point to a zero-valued timespec structure.

So when a programmer passes 0 to Select_File to poll for input without waiting, Select_File waits indefinitely instead.

Regarding INFTIM, citing the Linux Programmer's Manual, man 2 poll:

  Some implementations define the nonstandard constant INFTIM with the value -1 for use as a timeout for poll(). This constant is not provided in glibc.

So c-posix.c doesn't find INFTIM in the C headers, and then it stupidly defines INFTIM as 0 instead of -1. Bindings to standardized interfaces like poll or select should not depend on anything nonstandard like INFTIM.

**Comment by charlie5** [comment]
> The Ada Reference Manual specifies only that Duration exists and is a fixed-point type. I can't find anything about what it's supposed to represent. 
> 
From the Ada Reference Manual ...

"There is a predefined fixed point type named Duration, declared in the visible part of package Standard; a value of type Duration is used to represent the length of an interval of time, expressed in seconds."

(Just FYI. All your comments are valid.)

**Comment by Rombobeorn** [comment]
Ah, there it is: 9.6(7). It's an indexing failure. The index points only to A.1(43).

**Comment by Blady-Com** [comment]
> The Ada Reference Manual specifies only that Duration exists and is a fixed-point type. I can't find anything about what it's supposed to represent. However, the subprograms in posix.adb that handle Timespec and Duration assume that Duration represents seconds, so for consistency the rest of Florist should do the same. Therefore multiplying by 1000 in Poll is correct.
> 
> A default of -1 second for Poll is not the best choice. Citing the POSIX Programmer's Manual, man 3p poll:
> 
> If the value of timeout is -1, poll() shall block until a requested event occurs or until the call is interrupted.
> 
> The Posix manpage leaves other negative values unspecified, so Poll should make sure to pass exactly -1 ms to c_poll when Timeout = Wait_Indefinitely, not -1000 ms.

Thus, I propose the following code with a test for Wait_Indefinitely:

```ada
   procedure Poll
     (Files          : in out Poll_FD_Array;
      Response_Count : out    Natural;
      Timeout        : Duration := Wait_Indefinitely) is
   begin
      if Timeout /= Wait_Indefinitely then
         Response_Count := Natural (Check_NNeg (c_poll (
            fds     => Files (Files'First).C'Unchecked_Access,
            nfds    => unsigned (Files'Length),
            timeout => int (Long_Long_Integer (Timeout * 1000)))));
      else
         Response_Count := Natural (Check_NNeg (c_poll (
            fds     => Files (Files'First).C'Unchecked_Access,
            nfds    => unsigned (Files'Length),
            timeout => -1)));
      end if;
   end Poll;
```
 
> Wait_Indefinitely = 0 causes a problem with Select_File too. Citing the POSIX Programmer's Manual, man 3p pselect:
> 
> To effect a poll, the timeout parameter should not be a null pointer, and should point to a zero-valued timespec structure.
> 
> So when a programmer passes 0 to Select_File to poll for input without waiting, Select_File waits indefinitely instead.
> 
> Regarding INFTIM, citing the Linux Programmer's Manual, man 2 poll:
> 
> Some implementations define the nonstandard constant INFTIM with the value -1 for use as a timeout for poll(). This constant is not provided in glibc.
> 
> So c-posix.c doesn't find INFTIM in the C headers, and then it stupidly defines INFTIM as 0 instead of -1. Bindings to standardized interfaces like poll or select should not depend on anything nonstandard like INFTIM.

Thus, I propose the following code with -1 as default value for Wait_Indefinitely:
```
#ifdef INFTIM
  GCST("INFTIM", INFTIM);
#else
  GDFLT("INFTIM",-1);
#endif
```

What is your feedback?

**Comment by charlie5** [comment]
> 
> Thus, I propose the following code with a test for Wait_Indefinitely:
> 
> ```ada
>    procedure Poll
>      (Files          : in out Poll_FD_Array;
>       Response_Count : out    Natural;
>       Timeout        : Duration := Wait_Indefinitely) is
>    begin
>       if Timeout /= Wait_Indefinitely then
>          Response_Count := Natural (Check_NNeg (c_poll (
>             fds     => Files (Files'First).C'Unchecked_Access,
>             nfds    => unsigned (Files'Length),
>             timeout => int (Long_Long_Integer (Timeout * 1000)))));
>       else
>          Response_Count := Natural (Check_NNeg (c_poll (
>             fds     => Files (Files'First).C'Unchecked_Access,
>             nfds    => unsigned (Files'Length),
>             timeout => -1)));
>       end if;
>    end Poll;
> ```
>

This looks good to me. Perhaps you might use a conditional expression, as in ...

```ada
    procedure Poll
      (Files          : in out Poll_FD_Array;
       Response_Count : out    Natural;
       Timeout        : Duration := Wait_Indefinitely) is
    begin
          Response_Count := Natural (Check_NNeg (c_poll (
             fds     => Files (Files'First).C'Unchecked_Access,
             nfds    => unsigned (Files'Length),
             timeout => (if Timeout = Wait_Indefinitely then -1 
                                                        else int (Long_Long_Integer (Timeout * 1000))))));
    end Poll;
```

 
> 
> Thus, I propose the following code with -1 as default value for Wait_Indefinitely:
> 
> ```
> #ifdef INFTIM
>   GCST("INFTIM", INFTIM);
> #else
>   GDFLT("INFTIM",-1);
> #endif
> ```
> 
> What is your feedback?

I'd be tempted to drop INFTIME altogether and simply use ...

Wait_Indefinitely : constant Duration := -1.0;

**Comment by Rombobeorn** [comment]
Blady-Com wrote:
> I propose the following code with a test for Wait_Indefinitely:
> 
> ```ada
>    procedure Poll
>      (Files          : in out Poll_FD_Array;
>       Response_Count : out    Natural;
>       Timeout        : Duration := Wait_Indefinitely) is
>    begin
>       if Timeout /= Wait_Indefinitely then
>          Response_Count := Natural (Check_NNeg (c_poll (
>             fds     => Files (Files'First).C'Unchecked_Access,
>             nfds    => unsigned (Files'Length),
>             timeout => int (Long_Long_Integer (Timeout * 1000)))));
>       else
>          Response_Count := Natural (Check_NNeg (c_poll (
>             fds     => Files (Files'First).C'Unchecked_Access,
>             nfds    => unsigned (Files'Length),
>             timeout => -1)));
>       end if;
>    end Poll;
> ```

This should work.

Rod Kay wrote:
> Perhaps you might use a conditional expression, as in ...
> 
> ```ada
>     procedure Poll
>       (Files          : in out Poll_FD_Array;
>        Response_Count : out    Natural;
>        Timeout        : Duration := Wait_Indefinitely) is
>     begin
>           Response_Count := Natural (Check_NNeg (c_poll (
>              fds     => Files (Files'First).C'Unchecked_Access,
>              nfds    => unsigned (Files'Length),
>              timeout => (if Timeout = Wait_Indefinitely then -1 
>                          else int (Long_Long_Integer (Timeout * 1000))))));
>     end Poll;
> ```

This is even better, unless compatibility with Ada 2005 is desired.

Blady-Com wrote:
> I propose the following code with -1 as default value for Wait_Indefinitely:
> ```
> #ifdef INFTIM
>   GCST("INFTIM", INFTIM);
> #else
>   GDFLT("INFTIM",-1);
> #endif
> ```

As long as Florist defines INFTIM even when the C headers don't, -1 is
probably a better default than 0. Portable code should avoid using it
though. INFTIM is nonstandard, so a C library could use that name for
anything and not be wrong. Perhaps some vendor will decide to provide
an INtegrated Fourier Transform IMplementation some day?

Rod Kay wrote:
> I'd be tempted to drop INFTIME altogether and simply use ...
> 
> Wait_Indefinitely : constant Duration := -1.0;

I agree. Wait_Indefinitely should be negative regardless of what value
INFTIM might have in C. (Any negative value will do after the above
change to Poll. If you like, you could use -Duration'Small to make the
machine value FFFFFFFFFFFFFFFF.)

**Comment by Blady-Com** [comment]
Thanks for your contribution, I prefer to keep maximal compatibility with Ada 95.
Changes in this [commit](https://github.com/Blady-Com/florist/commit/88ba3199fa71487988e438f888f1a95c6d4a55dc).
